name: Build WebRTC

on:
  workflow_dispatch:

jobs:
    build:
        name: Build WebRTC
        runs-on: ubuntu-latest

        steps:
          - name: "Fetch sources"
            env:
                WEBRTC_COMMIT_ID: a2e33ed8808384ed46adb5ee3e0f8a2932645655
            run: |
                git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
                export PATH=$PWD/depot_tools:$PATH
                mkdir webrtc
                cd webrtc
                fetch --no-hooks webrtc
                cd src/
                git checkout ${{ env.WEBRTC_COMMIT_ID }}
                cd ..
                gclient sync -n
          - name: "Build release"
            run: |
                gn gen out/Release --args='rtc_use_dummy_audio_file_devices=true is_debug=false rtc_include_tests=false treat_warnings_as_errors=false use_rtti=true is_component_build=false enable_iterator_debugging=false use_sysroot=false use_custom_libcxx=false use_custom_libcxx_for_host=false is_clang=false rtc_build_tools=false rtc_enable_symbol_export=true'
                autoninja -C out/Release builtin_video_encoder_factory builtin_video_decoder_factory webrtc rtc_internal_video_codecs fake_video_codecs